# $line_break gives you the two lines
format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$fill\
$cmd_duration\
$line_break\
$jobs\
$battery\
$container\
$character\
"""

# Shell level is good if you open fish in fish for example
# In sway, base shell level is 2. Every new one would spawn an additional symbol
[shlvl]
disabled = false
repeat = true
repeat_offset = 2
symbol = '󱞣  '
format = '[$symbol]($style)'

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
format = '[$branch(:$remote_branch)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = '[󰦎 $count ](bold red)'
stashed = '[*$count ](bold cyan)'
deleted = '[󰩹 $count ](bold red)'
renamed = '[󰑕 $count ](bold yellow)'
modified = '[!$count ](bold yellow)'
staged = '[+$count ](bold green)'
untracked = '[?$count ](bold blue)'
ahead = '[ $count](bold green)'
behind = '[ $count](bold green)'
diverged = '⇕⇡ $ahead_count⇣ $behind_count'

[fill]
symbol = ' '

[cmd_duration]
min_time = 2_000
format = '[$duration]($style) '

[jobs]
format = '[$symbol($number)]($style)'
